name: Run Server Tests And Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.4' 

      - name: Run tests
        working-directory: ./server
        run:  go test -tags "fts5" -v ./...
        
      - name: Write SSH key to file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Cloudflared SSH Deplot
        uses: and-fm/cloudflared-ssh-action@v3.1.2
        with:
          hostname: ssh.ramizabdulla.me
          username: miz
          private_key_filename: ~/.ssh/deploy_key
          command: |
            cd /home/miz/dev/self-host/go-webcrawler
            git pull
            docker compose up -d --build domainsearch_api
